=== EliteThief/ProjektXML/ProjektXML.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- definition of simple elements -->
<xs:element name="Imie" type="xs:string"/>


<xs:element name="Nazwisko">
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z ]+"/>
			<xs:whiteSpace value="replace"/>
		</xs:restriction>
  </xs:simpleType>
</xs:element>

<xs:element name="DataPodpisania" type="xs:date"/>
<xs:element name="DataZakonczenia" type="xs:date"/>

<xs:element name="Email">
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="[^@]+@[^\.]+\..+"/>
		</xs:restriction>
  </xs:simpleType>
</xs:element>

<xs:element name="Tytul" type="xs:string"/>

<xs:element name="Wytwornia" type="xs:string"/>


<xs:element name="Miejsce">
	<xs:simpleType>
		<xs:restriction base="xs:integer">
			<xs:pattern value="[1-9]"/>
		</xs:restriction>
  </xs:simpleType>
</xs:element>

<xs:element name="Napoj">
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z0-9-]+"/>
		</xs:restriction>
  </xs:simpleType>
</xs:element>

<xs:element name="Przekaska" type="xs:string"/>


<!-- definition of attributes -->
<xs:attribute name="Plec">
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="M|K"/>
		</xs:restriction>
	</xs:simpleType>
 </xs:attribute>
<xs:attribute name="Typ">
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="Zlecenie|Prace|Dzielo"/>
		</xs:restriction>
	</xs:simpleType>
</xs:attribute>
<xs:attribute name="Kategoria">
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="([A-Za-z])*"/>
		</xs:restriction>
	</xs:simpleType>
 </xs:attribute>
 
<xs:attribute name="NrSali">
	<xs:simpleType>
		<xs:restriction base="xs:integer">
			<xs:maxInclusive value="10"/>
			<xs:minInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
 </xs:attribute>
 
<xs:attribute name="Numer">
	<xs:simpleType>
		<xs:restriction base="xs:integer">
			<xs:maxInclusive value="10"/>
			<xs:minInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
 </xs:attribute>

<!-- definition of complex elements -->

	<xs:element name="Umowa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DataPodpisania"/>
				<xs:element ref="DataZakonczenia"/>
			</xs:sequence>
			<xs:attribute ref="Typ" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="Pracownik">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Imie"/>
				<xs:element ref="Nazwisko"/>
				<xs:element ref="Umowa"/>
				<xs:element ref="Email" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute ref="Plec" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="Pracownicy">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Pracownik" minOccurs="0" maxOccurs="10"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Rezyser">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Imie"/>
				<xs:element ref="Nazwisko"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Aktor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Imie"/>
				<xs:element ref="Nazwisko"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Obsada">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Aktor" minOccurs="0" maxOccurs="10"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Film">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Tytul"/>
				<xs:element ref="Rezyser"/>
				<xs:element ref="Wytwornia"/>
				<xs:element ref="Obsada"/>
			</xs:sequence>
			<xs:attribute ref="Kategoria" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="Filmy">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Film" minOccurs="0" maxOccurs="10"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Rzad">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Miejsce" minOccurs="0" maxOccurs="10"/>
			</xs:sequence>
			<xs:attribute ref="Numer" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="Sala">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Rzad" minOccurs="0" maxOccurs="10"/>
			</xs:sequence>
			<xs:attribute ref="NrSali" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="SaleKinowe">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Sala" minOccurs="0" maxOccurs="10"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Napoje">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Napoj" minOccurs="0" maxOccurs="10"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Przekaski">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Przekaska" minOccurs="0" maxOccurs="10"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Bar">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Napoje"/>
				<xs:element ref="Przekaski"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Klient">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Imie"/>
				<xs:element ref="Nazwisko"/>
				<xs:element ref="Email"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Klienci">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Klient" minOccurs="0" maxOccurs="10"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Kino">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Pracownicy"/>
				<xs:element ref="Filmy"/>
				<xs:element ref="SaleKinowe"/>
				<xs:element ref="Bar"/>
				<xs:element ref="Klienci"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== EliteThief/ProjektXML/ProjektXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="ProjektXML.xsl"?>
<Kino xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ProjektXML.xsd">
	<Pracownicy>
		<Pracownik Plec='M'>
			<Imie>Piotr</Imie>
			<Nazwisko>Fornal</Nazwisko>
			<Umowa Typ='Zlecenie'>
				<DataPodpisania>2019-06-17</DataPodpisania>
				<DataZakonczenia>2021-06-18</DataZakonczenia>		
			</Umowa>
			<Email>piotrfornal1997@gmail.com</Email>
		</Pracownik>

		<Pracownik Plec='M'>
			<Imie>Mateusz</Imie>
			<Nazwisko>Jendernal</Nazwisko>
			<Umowa Typ='Prace' >
				<DataPodpisania>2019-07-23</DataPodpisania>
				<DataZakonczenia>2020-10-23</DataZakonczenia>
			</Umowa>
			<Email>mateuszjendernal@gmail.com</Email> 
		</Pracownik>

		<Pracownik Plec='K'>
			<Imie>Aleksandra</Imie>
			<Nazwisko>Fornal</Nazwisko>
			<Umowa Typ = 'Zlecenie'>
				<DataPodpisania>2019-01-01</DataPodpisania>
				<DataZakonczenia>2020-12-31</DataZakonczenia>
			</Umowa>
			<Email>aleksandraWitkowska@wp.pl</Email> 
		</Pracownik>

		<Pracownik Plec='K'>
			<Imie>Karolina</Imie>
			<Nazwisko>Wyszkoni</Nazwisko>
			<Umowa Typ = 'Zlecenie'>
				<DataPodpisania>2018-12-12</DataPodpisania>
				<DataZakonczenia>2022-12-30</DataZakonczenia>
			</Umowa>
			<Email>karo99@o2.pl</Email>	
		</Pracownik>
	</Pracownicy>

	<Filmy>
		<Film Kategoria='Dramat'>
			<Tytul>Joker</Tytul>
			<Rezyser>
				<Imie>Todd</Imie> 
				<Nazwisko>Phillips</Nazwisko>
			</Rezyser>
			<Wytwornia>A Joint Effort Productions</Wytwornia>
			<Obsada>
				<Aktor>
					<Imie>Joaquin</Imie>
					<Nazwisko>Phoenix</Nazwisko> 
				</Aktor>

				<Aktor>
					<Imie>Robert</Imie>
					<Nazwisko>De Niro</Nazwisko>  
				</Aktor>

				<Aktor>
					<Imie>Frances</Imie>
					<Nazwisko>Conroy</Nazwisko>
				</Aktor>

				<Aktor>
					<Imie>Leigh</Imie>
					<Nazwisko>Gill</Nazwisko>
				</Aktor> 
			</Obsada>
		</Film>

		<Film Kategoria='Akcja'>   
			<Tytul>Tyler Rake: Ocalenie</Tytul>
			<Rezyser>
				<Imie>Sam</Imie>
				<Nazwisko>Hargrave</Nazwisko>
			</Rezyser>
			<Wytwornia>India Take One Productions</Wytwornia>
			<Obsada>
				<Aktor>
					<Imie>Chris</Imie>
					<Nazwisko>Hemsworth</Nazwisko>
				</Aktor>

				<Aktor>
					<Imie>Randeep</Imie>
					<Nazwisko>Hooda</Nazwisko>
				</Aktor> 

				<Aktor>
					<Imie>Golshifteh</Imie>
					<Nazwisko>Farahani</Nazwisko>
				</Aktor>

				<Aktor>
					<Imie>David</Imie>
					<Nazwisko>Harbour</Nazwisko>
				</Aktor>
			</Obsada>
		</Film>

		<Film Kategoria='sensacyjny'>
			<Tytul>Skok Stulecia</Tytul>
			<Rezyser>
				<Imie>Christian</Imie> 
				<Nazwisko>Gudegast</Nazwisko>
			</Rezyser> 
			<Wytwornia>Atmosphere Entertainment MM</Wytwornia>
			<Obsada>
				<Aktor>
					<Imie>Pablo</Imie>
					<Nazwisko>Schreiber</Nazwisko> 
				</Aktor>

				<Aktor>
					<Imie>Gerard</Imie>
					<Nazwisko>Butler</Nazwisko>
				</Aktor>

				<Aktor>
					<Imie>O'Shea</Imie>
					<Nazwisko>Jackson Jr</Nazwisko>
				</Aktor>

				<Aktor>
					<Imie>Mo</Imie>
					<Nazwisko>McRae</Nazwisko>
				</Aktor>
			</Obsada>
		</Film>
	</Filmy>
	<SaleKinowe>
		<Sala NrSali ='1'> 
			<Rzad Numer='1'>
				<Miejsce>1</Miejsce>
				<Miejsce>2</Miejsce> 
				<Miejsce>3</Miejsce>
				<Miejsce>4</Miejsce>
				<Miejsce>5</Miejsce>
			</Rzad>
			<Rzad Numer='2'>
				<Miejsce>1</Miejsce>
				<Miejsce>2</Miejsce>
				<Miejsce>3</Miejsce>
				<Miejsce>4</Miejsce>
				<Miejsce>5</Miejsce>
			</Rzad>
			<Rzad Numer='3'>
				<Miejsce>1</Miejsce>
				<Miejsce>2</Miejsce>
				<Miejsce>3</Miejsce>
				<Miejsce>4</Miejsce>
				<Miejsce>5</Miejsce>
			</Rzad>
			<Rzad Numer='4'>
				<Miejsce>1</Miejsce>
				<Miejsce>2</Miejsce>
				<Miejsce>3</Miejsce>
				<Miejsce>4</Miejsce>
				<Miejsce>5</Miejsce>
			</Rzad>
		</Sala>
		<Sala NrSali ='2'>
			<Rzad Numer='1'>
				<Miejsce>1</Miejsce>
				<Miejsce>2</Miejsce>
				<Miejsce>3</Miejsce>
				<Miejsce>4</Miejsce>
				<Miejsce>5</Miejsce>
			</Rzad>
			<Rzad Numer='2'>
				<Miejsce>1</Miejsce>
				<Miejsce>2</Miejsce>
				<Miejsce>3</Miejsce>
				<Miejsce>4</Miejsce>
				<Miejsce>5</Miejsce>
			</Rzad>
			<Rzad Numer='3'>
				<Miejsce>1</Miejsce>
				<Miejsce>2</Miejsce>
				<Miejsce>3</Miejsce>
				<Miejsce>4</Miejsce>
				<Miejsce>5</Miejsce>
			</Rzad>
			<Rzad Numer='4'>
				<Miejsce>1</Miejsce>
				<Miejsce>2</Miejsce>
				<Miejsce>3</Miejsce>
				<Miejsce>4</Miejsce>
				<Miejsce>5</Miejsce>
			</Rzad>
		</Sala>
		<Sala NrSali ='3'>
			<Rzad Numer='1'>
				<Miejsce>1</Miejsce>
				<Miejsce>2</Miejsce>
				<Miejsce>3</Miejsce>
				<Miejsce>4</Miejsce>
				<Miejsce>5</Miejsce>
			</Rzad>
			<Rzad Numer='2'>
				<Miejsce>1</Miejsce>
				<Miejsce>2</Miejsce>
				<Miejsce>3</Miejsce>
				<Miejsce>4</Miejsce>
				<Miejsce>5</Miejsce>
			</Rzad>
			<Rzad Numer='3'>
				<Miejsce>1</Miejsce>
				<Miejsce>2</Miejsce>
				<Miejsce>3</Miejsce>
				<Miejsce>4</Miejsce>
				<Miejsce>5</Miejsce>
			</Rzad>
			<Rzad Numer='4'>
				<Miejsce>1</Miejsce>
				<Miejsce>2</Miejsce>
				<Miejsce>3</Miejsce>
				<Miejsce>4</Miejsce>
				<Miejsce>5</Miejsce>
			</Rzad>
		</Sala>
		<Sala NrSali ='4'>
			<Rzad Numer='1'>
				<Miejsce>1</Miejsce>
				<Miejsce>2</Miejsce>
				<Miejsce>3</Miejsce>
				<Miejsce>4</Miejsce>
				<Miejsce>5</Miejsce>
			</Rzad>
			<Rzad Numer='2'>
				<Miejsce>1</Miejsce>
				<Miejsce>2</Miejsce>
				<Miejsce>3</Miejsce>
				<Miejsce>4</Miejsce>
				<Miejsce>5</Miejsce>
			</Rzad>
			<Rzad Numer='3'>
				<Miejsce>1</Miejsce>
				<Miejsce>2</Miejsce>
				<Miejsce>3</Miejsce>
				<Miejsce>4</Miejsce>
				<Miejsce>5</Miejsce>
			</Rzad>
			<Rzad Numer='4'>
				<Miejsce>1</Miejsce>
				<Miejsce>2</Miejsce>
				<Miejsce>3</Miejsce>
				<Miejsce>4</Miejsce>
				<Miejsce>5</Miejsce> 
			</Rzad>
		</Sala>
	</SaleKinowe>
	<Bar>
		<Napoje>
			<Napoj>Coca-Cola</Napoj> 
			<Napoj>Fanta</Napoj>
			<Napoj>Pepsi</Napoj>
			<Napoj>7UP</Napoj>			
		</Napoje>

		<Przekaski>
			<Przekaska>PopCorn</Przekaska>
			<Przekaska>Nachos</Przekaska> 
			<Przekaska>Chipsy</Przekaska>
		</Przekaski>
	</Bar>
	<Klienci>
		<Klient>
			<Imie>Gra≈ºyna</Imie>
			<Nazwisko>Kowalska</Nazwisko>
			<Email>SupiGrazi123@wp.pl</Email>
		</Klient>

		<Klient> 
			<Imie>Ariel</Imie>
			<Nazwisko>Najlepszy</Nazwisko>
			<Email>doprania@gmail.com</Email>
		</Klient>

		<Klient>
			<Imie>Dosia</Imie>
			<Nazwisko>Pralka</Nazwisko>
			<Email>Hiacynt@o2.pl</Email>
		</Klient>

		<Klient>
			<Imie>Mateusz</Imie>
			<Nazwisko>Jendernal</Nazwisko>
			<Email>KrytykFilmowy@gmail.com</Email>
		</Klient>

		<Klient>
			<Imie>Tatiana</Imie>
			<Nazwisko>Brzeszczyczykiewicz</Nazwisko>
			<Email>TatiBrzeczi@ug.edu.pl</Email>
		</Klient>
	</Klienci>
</Kino>
